### ISSUE TITLE
This looks great, but is there a way to export the model?

### ISSUE THREAD

**Issue by GOvEy1nw** [yushiang-demo/PanoToMesh#5]
Thank you for making this. There used to be some software that did it before, but it seems to have disappeared completely. I was just wondering if there's any way to export the model that is generated?

**Comment by tsengyushiang** [comment]
Export the model and texture is plan to released in v1.0.0(#1), however there isn't a exactly time. Here is some thoughts of how to make these features:

- For exporting a model, [RoomGeometry](three/core/RoomGeometry.js) handles triangle faces and indexes, but uv coordinate  is not defined in current code.

- For exporting a texture, [PanoramaRoom](three/components/PanoramaRoom/index.js) shows how to render a model with projective texture. Instead of rendering 3d points, use predefined uv as output of vertex shader will be able to generate a texture.

Hope that will help you with how to export the model and it would be nice to open a pull request.
